log:
  disabled: true
experimental:
  cache_file:
    enabled: true
  clash_api:
    external_controller: 0.0.0.0:9090
    external_ui: ui
    external_ui_download_detour: select
    external_ui_download_url: https://github.com/MetaCubeX/Yacd-meta/archive/gh-pages.zip
    secret: "123456"
inbounds:
  - address:
      - 172.18.0.1/30
      - fdfe:dcba:9876::1/126
    auto_route: true
    interface_name: tun0
    mtu: 9000
    stack: mixed
    strict_route: true
    tag: tun-in
    type: tun
dns:
  final: external
  strategy: prefer_ipv4
  reverse_mapping: true
  servers:
    - tag: external
      address: tls://8.8.8.8
      detour: select
    - tag: internal
      address: 223.5.5.5
      detour: direct
    - tag: dns_block
      address: rcode://refused
  rules:
    - outbound: any
      server: internal
route:
  # 默认的出站规则,就是一些很基本不调就上不了网的
  rules:
    - action: hijack-dns
      port: 53
    - action: hijack-dns
      protocol: dns
    - ip_is_private: true
      outbound: direct
    - outbound: block
      protocol:
        - quic
  # 默认出站节点不能改,很多配置下载需要代理,我设置的都是select
  final: select
  auto_detect_interface: true
outbounds:
  - tag: direct
    type: direct
  - tag: block
    type: block
