application:
  singbox:
    listen: http://192.168.1.2:9090
    secret: 123456
    work_dir: /opt/singbox/config
    config_path: /opt/singbox/config.json
    binary_path: /opt/singbox/singbox
    commands:
      boot_command:
        name: systemctl
        args:
          - start
          - sing-box
      stop_command:
        name: systemctl
        args:
          - stop
          - sing-box
      check_command:
        name: systemctl
        args:
          - status
          - sing-box
      reload_command:
        name: systemctl
        args:
          - reload
          - sing-box
      restart_command:
        name: systemctl
        args:
          - restart
          - sing-box

  server:
    user:
      username: sifulin
      password: ws
      email: 198296@qq.com
      code: 123456
      private_key: sifulin
    # ssl:
    #   public: /opt/singbox/config/cert.pem
    #   private: /opt/singbox/config/key.pem
