application:
  singbox:
    work_dir: /opt/singbox/config
    config_path: /opt/singbox/config.json
    binary_path: /opt/singbox/singbox
    commands:
      boot_command: 
        name: systemctl
        args:
          - start
          - sing-box
      stop_command: 
        name: systemctl
        args:
          - stop
          - sing-box
      check_command: 
        name: systemctl
        args:
          - status
          - sing-box
      reload_command: 
        name: systemctl
        args:
          - reload
          - sing-box
      restart_command: 
        name: systemctl
        args:
          - restart
          - sing-box

  server:
    interval: "* * * * *"
    user:
      username: sifulin
      password: wsr19990902
      email: 1982209396@qq.com
      code: 123456
      private_key: sifulin
    # ssl:
    #   public: /opt/singbox/config/cert.pem
    #   private: /opt/singbox/config/key.pem

configuration:
  providers:
    - name: "夜煞云"
      path: "https://45.137.180.216/api/v1/client/nyth?token=aa751df806caf70136e33c9310531fe6"
      detour: select
      remote: true
    - name: "github1"
      path: "C:/Users/19822/Downloads/20250119.yaml"
      detour: select
      remote: false
    # - name: "github2"
    #   path: "C:/Users/19822/Downloads/20250119.yaml1"
    #   detour: select
    #   remote: false
  rulesets:
    - type: remote
      path: https://github.com/MetaCubeX/meta-rules-dat/raw/sing/geo/geosite/cn.srs
      format: binary
      tag: china-site
      download_detour: select
      update_interval: 1d
      label: china
      china: true
      name_server: internal
    - type: remote
      path: https://github.com/MetaCubeX/meta-rules-dat/raw/sing/geo/geoip/cn.srs
      format: binary
      tag: china-ip
      download_detour: select
      update_interval: 1d
      label: china
      china: true
  templates:
    default:
      log:
        disabled: false
        timestamp: true
        output: singbox.log
      experimental:
        cache_file:
          enabled: true
        clash_api:
          external_controller: 0.0.0.0:9090
          external_ui: ui
          external_ui_download_detour: select
          external_ui_download_url: https://github.com/MetaCubeX/Yacd-meta/archive/gh-pages.zip
          secret: "123456"
      inbounds:
        - address:
            - 172.18.0.1/30
            - fdfe:dcba:9876::1/126
          auto_route: true
          interface_name: tun0
          mtu: 9000
          stack: mixed
          strict_route: true
          tag: tun-in
          type: tun
      dns:
        final: external
        strategy: prefer_ipv4
        reverse_mapping: true
        servers:
          - tag: external
            address: tls://8.8.8.8
            detour: select
          - tag: internal
            address: 192.168.1.2:5353
            detour: direct
          - tag: dns_block
            address: rcode://refused
        rules:
          - outbound:
              - any
            action: route
            server: internal
      route:
        # 默认的出站规则,就是一些很基本不调就上不了网的
        rules:
          - user:
              - bind
            action: route
            outbound: direct
          - action: hijack-dns
            port:
              - 53
          - action: hijack-dns
            protocol:
              - dns
          - action: route
            outbound: direct
            ip_is_private: true
          - protocol:
              - quic
            action: reject
        # 默认出站节点不能改,很多配置下载需要代理,我设置的都是select
        final: select
        auto_detect_interface: true
      outbounds:
        - tag: direct
          type: direct
      custom_outbounds:
        - tag: 香港
          type: shadowsocks
          method: chacha20-ietf-poly1305
          server: 127.0.0.1
          server_port: 443
          password: 123456dsaf
    ios:
      log:
        disabled: true
      experimental:
        cache_file:
          enabled: true
        clash_api:
          external_controller: 0.0.0.0:9090
          external_ui: ui
          external_ui_download_detour: select
          external_ui_download_url: https://github.com/MetaCubeX/Yacd-meta/archive/gh-pages.zip
          secret: "123456"
      inbounds:
        - address:
            - 172.18.0.1/30
            - fdfe:dcba:9876::1/126
          auto_route: true
          interface_name: tun0
          mtu: 9000
          stack: mixed
          strict_route: true
          tag: tun-in
          type: tun
      dns:
        final: external
        strategy: prefer_ipv4
        reverse_mapping: true
        servers:
          - tag: external
            address: tls://8.8.8.8
            detour: select
          - tag: internal
            address: 223.5.5.5
            detour: direct
          - tag: dns_block
            address: rcode://refused
        rules: [{ outbound: [any], action: route, server: internal }]

      route:
        # 默认的出站规则,就是一些很基本不调就上不了网的
        rules:
          [
            { action: hijack-dns, port: [53] },
            { action: hijack-dns, protocol: [dns] },
            { ip_is_private: true, action: route, outbound: direct },
            { protocol: [quic], action: reject },
          ]
        # 默认出站节点不能改,很多配置下载需要代理,我设置的都是select
        final: select
        auto_detect_interface: true
      outbounds:
        - tag: direct
          type: direct
        - tag: block
          type: block

